project="projectA"
project_env="dev"
confluent_environment="env-xrz8qx"
confluent_kafka_cluster="lkc-okqdox"
kafka_api_key="M7QV7TFLZVJJDUSH"
kafka_api_secret="z193jc0M5T1nhtGC8puXaAqK2mawWVcvK/biEjMXiZB4u5Dq6+xpcB4NUytwGPgj"
