# This is a basic workflow to help you get started with Actions

name: CI/CD with Terraform
on:
  push:
    branches: [ "main" ]

env:
  CONFLUENT_CLOUD_API_KEY: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
  CONFLUENT_CLOUD_API_SECRET: ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="region=us-west-2"
        working-directory: ./terraform
        
      - name: Setup Terraform variables
        working-directory: ./terraform
        id: vars
        run: |-
          cat > qut.terraform.tfvars <<EOF
          confluent_cloud_api_key = "${{ secrets.CONFLUENT_CLOUD_API_KEY }}"
          confluent_cloud_api_secret = "${{ secrets.CONFLUENT_CLOUD_API_SECRET }}"
          CLIENT_ID     = "${{ secrets.CLIENT_ID }}"
          CLIENT_SECRET = "${{ secrets.CLIENT_SECRET }}"
          kafka_api_key = "${{ secrets.KAFKA_API_KEY }}"
          kafka_api_secret = "${{ secrets.KAFKA_API_SECRET }}"
          EOF
          cat qut.terraform.tfvars
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -var-file=qut.terraform.tfvars -out=PLAN
        working-directory: ./terraform
      - name: Terraform Apply
        id: apply
        run: terraform apply PLAN
        working-directory: ./terraform
